# gcloud builds submit --config cloudbuild.yaml .
steps:
  # Build image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'asia-east1-docker.pkg.dev/golden-medium-471501-p8/cathay-demo-image/cathay-demo-frontend:k8s',
        '.'
      ]

  # Push k8s tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-east1-docker.pkg.dev/golden-medium-471501-p8/cathay-demo-image/cathay-demo-frontend:k8s'
      ]

images:
  - 'asia-east1-docker.pkg.dev/golden-medium-471501-p8/cathay-demo-image/cathay-demo-frontend:k8s'

options:
  logging: CLOUD_LOGGING_ONLY
